packages:
  - apps/*
  - backend
  - packages/*
  - web

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - cypress
  - esbuild
  - exifreader
  - msgpackr-extract
  - prisma
  - sharp
