name: Markdown Lint

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Copy custom rule to workspace
        run: |
          mkdir -p .vscode/rules
          cp .vscode/rules/heading-content-required.js .vscode/rules/
        
      - name: Check for empty headings
        run: npm run fix:headings
        
      - name: Run markdownlint
        run: npm run lint:md
        continue-on-error: false
        
      - name: Create Pull Request if changes were made
        if: failure() && github.event_name == 'push'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'docs: fix markdown formatting'
          title: 'Automated Markdown formatting fixes'
          body: |
            This PR fixes Markdown formatting issues automatically:
            - Ensures all headings have content
            - Applies consistent formatting
            
            Generated by the Markdown Lint workflow.
          branch: fix-markdown-formatting
          base: main